spring:
  profiles:
    active: prd

---

spring:
    ## (2)
    profiles: prd
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/yhs-tranfer
      username: postgres
      password: admin
    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: update
    thymeleaf:
    cache: false

security.basic.enabled: false
---
spring:
    ## (3)
    profiles: heroku
    datasource:
      driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      hibernate:
        ##ddl-auto: create-drop
        ddl-auto: update
        
    